<?php
if( function_exists('acf_add_local_field_group') ):

	acf_add_local_field_group(array(
		'key' => 'group_5ef4829e90fc7',
		'title' => 'Courses index Settings',
		'fields' => array(
			array(
				'key' => 'field_5efb8bfd8357d',
				'label' => 'Academic insitutions list',
				'name' => 'campus_order_academic_institutions_list',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => 'campus_order_academic_institutions_list campus_order_filter_items campus_manual_order_filter_items',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5ef4831e6d9a8',
				'label' => 'Filters List',
				'name' => 'filters_list',
				'type' => 'flexible_content',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layouts' => array(
					'layout_5ef4834eb5265' => array(
						'key' => 'layout_5ef4834eb5265',
						'name' => 'automatic_order',
						'label' => 'Automatic Order',
						'display' => 'block',
						'sub_fields' => array(
							array(
								'key' => 'field_5ef9b1c3501db',
								'label' => 'Order type',
								'name' => 'order_type',
								'type' => 'select',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'choices' => array(
									'alphabet' => 'Alphabet',
									'amount' => 'Amout of courses',
									'popularity' => 'Popularity',
								),
								'default_value' => false,
								'allow_null' => 0,
								'multiple' => 0,
								'ui' => 0,
								'return_format' => 'value',
								'ajax' => 0,
								'placeholder' => '',
							),
							array(
								'key' => 'field_5ef4835e6d9a9',
								'label' => 'Taxonomy',
								'name' => 'taxonomy',
								'type' => 'select',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => 'campus_manual_order_filter_tax',
									'id' => '',
								),
								'choices' => array(
									'subject' => 'Subjects',
									'language' => 'Languages',
									'tags_course' => 'Courses Tags',
									'areas_of_knowledge' => 'Learning Target',
									'age_strata' => 'Age Strata',
									'tags_knowledge' => 'Field Of Knowledge',
									'skill' => 'Skills',
									'course_duration' => 'Duration of the course',
								),
								'default_value' => false,
								'allow_null' => 1,
								'multiple' => 0,
								'ui' => 0,
								'return_format' => 'value',
								'ajax' => 0,
								'placeholder' => '',
							),
							array(
								'key' => 'field_5ef9b20e501dc',
								'label' => 'Exluded Items',
								'name' => 'terms_list',
								'type' => 'text',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => 'campus_order_filter_items campus_automatic_order_filter_items',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
						),
						'min' => '',
						'max' => '',
					),
					'layout_5ef487f024efb' => array(
						'key' => 'layout_5ef487f024efb',
						'name' => 'manual',
						'label' => 'Manual order',
						'display' => 'block',
						'sub_fields' => array(
							array(
								'key' => 'field_5ef487f024efc',
								'label' => 'Taxonomy',
								'name' => 'taxonomy',
								'type' => 'select',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => 'campus_manual_order_filter_tax',
									'id' => '',
								),
								'choices' => array(
									'subject' => 'Subjects',
									'language' => 'Languages',
									'tags_course' => 'Courses Tags',
									'areas_of_knowledge' => 'Learning Target',
									'age_strata' => 'Age Strata',
									'tags_knowledge' => 'Field Of Knowledge',
									'skill' => 'Skills',
									'course_duration' => 'Duration of the course',
								),
								'default_value' => false,
								'allow_null' => 1,
								'multiple' => 0,
								'ui' => 0,
								'return_format' => 'value',
								'ajax' => 0,
								'placeholder' => '',
							),
							array(
								'key' => 'field_5ef4889c24efe',
								'label' => 'Items',
								'name' => 'terms_list',
								'type' => 'text',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => 'campus_order_filter_items campus_manual_order_filter_items',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
						),
						'min' => '',
						'max' => '',
					),
				),
				'button_label' => 'Add Row',
				'min' => '',
				'max' => '',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'options_page',
					'operator' => '==',
					'value' => 'courses_index_settings',
				),
			),
			array(
				array(
					'param' => 'taxonomy',
					'operator' => '==',
					'value' => 'tags_course',
				),
			),
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'project',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
	));

endif;